### ISSUE TITLE
TypeError while running test.py

### ISSUE THREAD

**Issue by Davide-sd** [tensorlayer/adaptive-style-transfer#5]
I'm trying this implementation, but I'm having an error running the command `python3 test.py`. I never used tensorlayer, so I think I need help.

This is the traceback:

```
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    dec_net = decoder.decode(target_features, prefix="decoder/")
  File "/home/davide/Documents/Development/AI/adaptive-style-transfer/models.py", line 39, in decode
    net = UpSampling2dLayer(net, [2, 2], method=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorlayer/layers/convolution.py", line 509, in __init__
    size_h = size[0] * int(self.inputs.get_shape()[1])
TypeError: __int__ returned non-int (type NoneType)
```

 I'm using tensorlayer 1.8.1 and tensorflow 1.12.

**Comment by TianMingChen** [comment]
> I'm trying this implementation, but I'm having an error running the command `python3 test.py`. I never used tensorlayer, so I think I need help.
> 
> This is the traceback:
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 48, in <module>
>     dec_net = decoder.decode(target_features, prefix="decoder/")
>   File "/home/davide/Documents/Development/AI/adaptive-style-transfer/models.py", line 39, in decode
>     net = UpSampling2dLayer(net, [2, 2], method=1)
>   File "/usr/local/lib/python3.6/dist-packages/tensorlayer/layers/convolution.py", line 509, in __init__
>     size_h = size[0] * int(self.inputs.get_shape()[1])
> TypeError: __int__ returned non-int (type NoneType)
> ```
> 
> I'm using tensorlayer 1.8.1 and tensorflow 1.12.

Do you have solve this problem?

**Comment by zsdonghao** [comment]
would you try tl 1.14 ?

**Comment by TianMingChen** [comment]
> would you try tl 1.14 ?

it seems not have tensorlayer 1.14 Versions?

**Comment by Davide-sd** [comment]
Hello @TianMingChen ,

It's been a few months now... I did solve that problem but I'm not sure how. Probably I upgraded tensorlayer to a newer version. In my system I have installed version 1.11.1, and it worked as expected.

**Comment by TianMingChen** [comment]
> Hello @TianMingChen ,
> 
> It's been a few months now... I did solve that problem but I'm not sure how. Probably I upgraded tensorlayer to a newer version. In my system I have installed version 1.11.1, and it worked as expected.

Ok,thanks a lot!
